# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ericoin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('balance', models.PositiveIntegerField()),
                ('public_key', models.CharField(editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('index', models.PositiveIntegerField()),
                ('recipient_key', models.CharField(max_length=200)),
                ('sender_key', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='information',
            name='action',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
