# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ericoin', '0002_auto_20171229_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='public_key',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
